name: 小创作
description: '书写是一种创作，分享是一种美德'
meta_description: "小创作 关于技术和生活的思考"

markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://chriszou.com'
enable_sharing: false

# Details for the RSS feed generator
url:            'http://chriszou.com'
author:         '小创'

gems: [jekyll-paginate]
