name: 邹小创 个人博客
description: '关于生活和技术'
meta_description: "邹小创个人博客 关于生活和技术"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'

gems: [jekyll-paginate]
